plugins {
    kotlin("multiplatform") version "2.2.0"
    kotlin("plugin.serialization") version "2.2.0"
}

group = "org.btmonier"
version = "0.3.1"

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(21)
    
    jvm {
        mainRun {
            mainClass.set("org.btmonier.cli.MainKt")
        }
    }

    js(IR) {
        browser {
            commonWebpackConfig {
                cssSupport {
                    enabled.set(true)
                }
            }
            binaries.executable()
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
            }
        }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        val jvmMain by getting {
            dependencies {
                implementation("com.github.ajalt.clikt:clikt:4.4.0")
                implementation("com.github.librepdf:openpdf:2.0.2")
                // Apache Batik for SVG rendering
                implementation("org.apache.xmlgraphics:batik-transcoder:1.17")
                implementation("org.apache.xmlgraphics:batik-codec:1.17")
            }
        }
        val jvmTest by getting {
            dependencies {
                implementation(kotlin("test-junit"))
            }
        }
        val jsMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-html-js:0.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.9.0")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")
            }
        }
        val jsTest by getting {
            dependencies {
                implementation(kotlin("test-js"))
            }
        }
    }
}

// Task to generate BuildConfig.kt with version info for JS target
val generateBuildConfig by tasks.registering {
    group = "build"
    description = "Generate BuildConfig.kt with version information"

    val outputDir = layout.buildDirectory.dir("generated/kotlin/jsMain")
    val versionString = project.version.toString()

    outputs.dir(outputDir)

    doLast {
        val buildConfigDir = outputDir.get().asFile.resolve("org/btmonier")
        buildConfigDir.mkdirs()
        buildConfigDir.resolve("BuildConfig.kt").writeText(
            """
            |package org.btmonier
            |
            |/**
            | * Auto-generated build configuration.
            | * DO NOT EDIT - This file is generated by Gradle.
            | */
            |object BuildConfig {
            |    const val VERSION: String = "$versionString"
            |}
            """.trimMargin()
        )
    }
}

kotlin.sourceSets.named("jsMain") {
    kotlin.srcDir(layout.buildDirectory.dir("generated/kotlin/jsMain"))
}

tasks.named("compileKotlinJs") {
    dependsOn(generateBuildConfig)
}
